import { generateSpecifiedDates } from "../generateSnapshots";
import { SnapshotSeed } from "../types";

export const generateCustomSnapshots = (userId: number): SnapshotSeed[] => {
  const snapshots: SnapshotSeed[] = [];
  const specifiedDates = generateSpecifiedDates();
  specifiedDates.forEach((date) => {
    snapshots.push({
      title: `PP ${date.getMonth() + 1}/${date.getFullYear()}`,
      benchmark: "Permanent Portfolio",
      notes: "Test case generated by PI",
      userId,
      specifiedDate: date,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  return snapshots;
};
