/*
 * ACTIONS: REGISTER_SUCCESS, REGISTER_FAIL; LOGIN_SUCCESS, LOGIN_FAIL
 * SAGAS: REGISTER, LOGIN
 */
export const USER_TYPES = {
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER: "REGISTER",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};

// API Endpoints
export const API_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
};
