/*
 * ACTIONS: REGISTER_SUCCESS, REGISTER_FAIL; LOGIN_SUCCESS, LOGIN_FAIL
 * SAGAS: REGISTER, LOGIN
 */
export const USER_TYPES = {
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER: "REGISTER",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
};

// API Endpoints
const API_BASE_ROUTE = "http://localhost:3001";

export const API_ROUTES = {
  LOGIN: API_BASE_ROUTE + "/login",
  REGISTER: API_BASE_ROUTE + "/register",
};
