import db from "../../../models";
import { SnapshotAttributes } from "../../../models/snapshots";

export const shouldCustomUserUpdate = (): Promise<boolean> => {
  return new Promise(async (res, rej) => {
    try {
      let snapshots: SnapshotAttributes[] | null = null;
      const user = await db.Users.findOne({
        where: { email: "hello_world@gmail.com" },
      });

      if (user) {
        snapshots = await db.Snapshots.findAll({
          where: { userId: user.id },
        });
      }

      if (snapshots?.length === 5) {
        const oneYearOld = new Date();
        oneYearOld.setFullYear(oneYearOld.getFullYear() - 1);

        const accountTooOld = user.createdAt < oneYearOld;
        const hasCorrectSnapshots =
          snapshots[0].notes === "Test case generated by PI" &&
          snapshots[1].notes === "Test case generated by PI" &&
          snapshots[2].notes === "Test case generated by PI" &&
          snapshots[3].notes === "Test case generated by PI" &&
          snapshots[4].notes === "Test case generated by PI";

        if (hasCorrectSnapshots && !accountTooOld) {
          res(false);
        }
      }

      res(true);
    } catch (err) {
      console.log(err);
      rej(err);
    }
  });
};
